# Generated by Django 3.1.5 on 2021-01-29 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='peoplefollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
